name: Python Tests

on:
  push:
    branches:
      - main  # or specify other branches you want the tests to run on
  pull_request:
    branches:
      - main  # or specify other branches for pull requests

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # You can set the version of Python to match your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies, adjust if needed

    - name: Run tests with pytest
      run: |
        pytest tests/test_data_retriever.py  # Adjust this if your test file path is different
